#!/usr/bin/env bash
# youn.yfocus — optional helper.
# By default this script does NOT modify your Hyprland config.
# It only builds the bundled CLI if missing and prints manual hotkey instructions.
# Pass --apply to create a dedicated bindings file at ~/.config/hypr/apps/yfocus.conf
# (never touches ~/.config/hypr/bindings.lua).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APPLY=0
if [[ "${1:-}" == "--apply" || "${1:-}" == "--yes" ]]; then
  APPLY=1
fi

# --- auto-build CLI if missing -------------------------------------------
if [ ! -x "$REPO_ROOT/bin/yfocus" ]; then
  if command -v bun >/dev/null 2>&1; then
    echo "Building yfocus (no bundled binary found)..."
    (cd "$REPO_ROOT" && ./build.sh) || echo "Warning: build failed — try: ./build.sh"
  else
    echo "Note: no bundled binary and bun not found."
    echo "  On the plugin host: install bun (https://bun.sh) and run ./build.sh."
    echo "  Or set YFOCUS_BIN to a yfocus on PATH."
  fi
else
  echo "Bundled binary present: $REPO_ROOT/bin/yfocus"
fi

# --- hotkey instructions ---------------------------------------------------
EXAMPLE='-- youn.yfocus hotkeys (optional) — add to ~/.config/hypr/bindings.lua manually
-- or create ~/.config/hypr/apps/yfocus.conf with the block below
-- youn.yfocus:start
o.bind("SUPER + E", "Pop current focus task", "yfocus pop")
o.bind("SUPER + SHIFT + T", "yfocus jump", "omarchy-shell shell toggle youn.yfocus '\''{\"mode\":\"jump\"}'\''")
o.bind("SUPER + ALT + T", "yfocus add", "omarchy-shell shell toggle youn.yfocus '\''{\"mode\":\"add\"}'\''")
o.bind("SUPER + CTRL + T", "Open yfocus", "omarchy-shell shell toggle youn.yfocus '\''{\"mode\":\"manage\"}'\''")
-- youn.yfocus:end'

if (( APPLY )); then
  TARGET="${HOME}/.config/hypr/apps/yfocus.conf"
  mkdir -p "$(dirname "$TARGET")"
  if [ -f "$TARGET" ]; then
    echo "Backing up existing $TARGET -> $TARGET.bak"
    cp -a "$TARGET" "$TARGET.bak"
  fi
  cat > "$TARGET" <<EOF
-- youn.yfocus hotkeys — generated by hooks/install.sh --apply
-- Edit or remove this file to change bindings. This file is NOT managed by the plugin at runtime.
o.bind("SUPER + E", "Pop current focus task", "yfocus pop")
o.bind("SUPER + SHIFT + T", "yfocus jump", "omarchy-shell shell toggle youn.yfocus '{\"mode\":\"jump\"}'")
o.bind("SUPER + ALT + T", "yfocus add", "omarchy-shell shell toggle youn.yfocus '{\"mode\":\"add\"}'")
o.bind("SUPER + CTRL + T", "Open yfocus", "omarchy-shell shell toggle youn.yfocus '{\"mode\":\"manage\"}'")
EOF
  echo "Wrote $TARGET"
  echo "If your Hyprland setup sources ~/.config/hypr/apps/*.conf, reload with: hyprctl reload"
else
  echo ""
  echo "Hotkeys are NOT installed automatically (to avoid touching your bindings)."
  echo "To add them manually, put this in ~/.config/hypr/bindings.lua or ~/.config/hypr/apps/yfocus.conf:"
  echo ""
  printf '%s\n' "$EXAMPLE"
  echo ""
  echo "Or run: ./hooks/install.sh --apply  (creates apps/yfocus.conf, backs up existing)"
fi

echo ""
echo "yfocus CLI: the plugin uses the bundled bin/yfocus. For 'yfocus pop' on PATH:"
echo "  ln -sf \"\$HOME/.config/omarchy/plugins/youn.yfocus/bin/yfocus\" \"\$HOME/.local/bin/yfocus\"  # optional, manual"
